architectury {
    common("fabric", "neoforge")
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabricLoaderVersion}"
    modApi "dev.architectury:architectury:${rootProject.architecturyVersion}"
    implementation "com.st0x0ef.stellaris:stellaris-common-${minecraftVersion}:${stellarisVersion}"
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.modid
            from components.java
        }
    }
}